using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using smartOffice_Models;
using SmartAnything;
using System.Data;

namespace smartOffice_BL
{
    public class u_SysSetup_BL
    {
        public u_SysSetup getSetupParams()
        {
            return new u_SysSetup_DL().PopulateSetupParams();
        }


        /// <summary>
        /// Get Deatails in u_SysSetup table by accessing the Data Access Layer
        /// </summary>
        /// <returns>object of u_SysSetup class in smartOffice_Models fill with details</returns>
        public u_SysSetup getDetails()
        {
            try
            {
                u_SysSetup_DL objSysDL = new u_SysSetup_DL();
                return objSysDL.getDetails();
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }



        /// <summary>
        /// get auto generate details in u_SysSetup table by accessing the Data Access Layer
        /// modified by Peshala Rupasingha 2013/12/12
        /// </summary>
        /// <returns>object of u_SysSetup class in smartOffice_Models fill with details</returns>
        public DataTable getAutoGenerateData(string type)
        {
            try
            {
                u_SysSetup_DL objSysDL = new u_SysSetup_DL();
               
                    return objSysDL.AcessSP(type);
                    //return objSysDL.AcessnewSP();
                
               
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }




        /// <summary>
        /// when user close the form without saving add Id to the cancelAutoNumber table
        /// modified by Peshala Rupasingha 2013/12/13
        /// </summary>
        /// <param name="ID">Cancel Id</param>
        /// <param name="type">Form type</param>
        public void AddToCancelTable(string ID,string type)
        {
            try
            {
                u_SysSetup_DL objSysDL = new u_SysSetup_DL();
                objSysDL.AddToCancelTable(ID,type);
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }


        /// <summary>
        /// check whether Id should be autogenerated or not
        /// modified by Peshala Rupasingha 2013/12/17
        /// </summary>
        /// <param name="type">Form type</param>
        /// <returns>if autogenerated returns 1 else returns 0</returns>
        public int getAutoGenerate(string type)
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
             return objSysDL.getAutoGenerateData(type);
        }

        /// <summary>
        /// check Maintain Stock Lot 
        /// modified by Sanjeewa 05-18-2015
        /// </summary>
        /// <param name="type">Form type</param>
        /// <returns>if maintain stocklot  returns 1 else returns 0</returns>
        public int GetMaintainStockLot()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.GetMaintainStockLot();
        }

         /// <summary>
        /// get the level id for create lat codes
        /// </summary>
        /// <returns>string value level id</returns>
        public string getLotLevel()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.getLotLevel();
        }


        /// <summary>
        ///  Call the GetGLConnect method in the data Access Layer
        /// </summary>
        /// <returns>return selected integer value</returns>
        public int GetGLConnect()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.GetGLConnect();

        }

        /// <summary>
        ///  Call the getIsAverageCostBased method in the data Access Layer
        /// </summary>
        /// <returns>return selected integer value</returns>
        public int getIsAverageCostBased()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.getIsAverageCostBased();

        }

        /// <summary>
        ///  Call the GetGoodInTransferAccCode method in the data Access Layer
        /// </summary>
        /// <returns>return selected string value</returns>
        public string GetGoodInTransferAccCode()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.GetGoodInTransferAccCode();

        }

        /// <summary>
        ///  Call the GetAdditionalAccCode method in the data Access Layer
        /// </summary>
        /// <returns>return selected string value</returns>
        public string GetAdditionalAccCode()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.GetAdditionalAccCode();

        }

        /// <summary>
        ///  Call the GetStaffUsageAccCode method in the data Access Layer
        /// </summary>
        /// <returns>return selected string value</returns>
        public string GetStaffUsageAccCode()
        {
            u_SysSetup_DL objSysDL = new u_SysSetup_DL();
            return objSysDL.GetStaffUsageAccCode();

        }

    }
}
