//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RIT_ATEntities2 : DbContext
    {
        public RIT_ATEntities2()
            : base("name=RIT_ATEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_packingdet> T_packingdet { get; set; }
        public DbSet<T_packinghead> T_packinghead { get; set; }
        public DbSet<T_CreditNoteHead> T_CreditNoteHead { get; set; }
        public DbSet<T_OrderFormHead> T_OrderFormHead { get; set; }
        public DbSet<T_SalesCustomerAlloc> T_SalesCustomerAlloc { get; set; }
        public DbSet<T_SalesItemAlloc> T_SalesItemAlloc { get; set; }
        public DbSet<T_CustomerItemAlloc> T_CustomerItemAlloc { get; set; }
        public DbSet<T_DIliveryHed> T_DIliveryHed { get; set; }
        public DbSet<T_DIliveryAudit> T_DIliveryAudit { get; set; }
        public DbSet<T_OrderTracking> T_OrderTracking { get; set; }
        public DbSet<T_CNGrouping> T_CNGrouping { get; set; }
        public DbSet<T_CNBreak> T_CNBreak { get; set; }
        public DbSet<T_SalesAllocDet> T_SalesAllocDet { get; set; }
        public DbSet<T_SalesAllocHead> T_SalesAllocHead { get; set; }
        public DbSet<T_DiliveryDet> T_DiliveryDet { get; set; }
        public DbSet<T_CNParts> T_CNParts { get; set; }
    }
}
