//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CNBreak
    {
        public string DocNo { get; set; }
        public string ItemCode { get; set; }
        public string Namex { get; set; }
        public Nullable<decimal> InvQTY { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
        public string Userx { get; set; }
        public Nullable<bool> Grouped { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
    }
}
