//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CNParts
    {
        public string CNno { get; set; }
        public string TagNumber { get; set; }
        public string ItemCode { get; set; }
        public string PartCode { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<bool> Saved { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string ProcessedUser { get; set; }
    }
}
