//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CreditNoteHead
    {
        public string DocNo { get; set; }
        public string CompCode { get; set; }
        public string LocaCode { get; set; }
        public string OFNo { get; set; }
        public string InvNo { get; set; }
        public string Dono { get; set; }
        public string CustomerID { get; set; }
        public string TypeX { get; set; }
        public string AuditUser { get; set; }
        public string Statusx { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
        public string ManualID { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public string PackingList { get; set; }
        public string DeliveryStatus { get; set; }
        public string AgentStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string ProcessedUser { get; set; }
        public Nullable<bool> Grouped { get; set; }
        public Nullable<System.DateTime> GroupedDate { get; set; }
        public string GroupedUser { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedUser { get; set; }
        public Nullable<bool> PartEnterComplete { get; set; }
        public Nullable<System.DateTime> PartEnterCompleteDate { get; set; }
        public string PartEnterCompleteUser { get; set; }
    }
}
