//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DiliveryDet
    {
        public string DoNo { get; set; }
        public string Item { get; set; }
        public string ItemNamex { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Carton { get; set; }
        public Nullable<decimal> ActualCartons { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Pass { get; set; }
        public bool IsCNitem { get; set; }
        public string CNNumber { get; set; }
    }
}
