//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrderTracking
    {
        public string OFNo { get; set; }
        public string CompCode { get; set; }
        public string LocaCode { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> CustomerDIscRate { get; set; }
        public string SalesMan { get; set; }
        public Nullable<int> OFApproved { get; set; }
        public string OFApprovedUser { get; set; }
        public Nullable<System.DateTime> OFApprovedDate { get; set; }
        public Nullable<decimal> OFNoOfPrints { get; set; }
        public string OFPrintUser { get; set; }
        public Nullable<int> InvCreated { get; set; }
        public string InvNo { get; set; }
        public Nullable<decimal> InvAmount { get; set; }
        public Nullable<int> InvApproved { get; set; }
        public string InvApprovedUser { get; set; }
        public Nullable<System.DateTime> InvApprovedDate { get; set; }
        public Nullable<decimal> InvNoOfPrints { get; set; }
        public string InvPrintUser { get; set; }
        public Nullable<int> DOCreated { get; set; }
        public string DONo { get; set; }
        public Nullable<decimal> DOAmount { get; set; }
        public string DOMultipleNO { get; set; }
        public Nullable<int> DOProcessed { get; set; }
        public string DOProcessedUser { get; set; }
        public Nullable<System.DateTime> DOProcessedDate { get; set; }
        public Nullable<int> DOApproved { get; set; }
        public string DOApprovedUser { get; set; }
        public Nullable<System.DateTime> DOApprovedDate { get; set; }
        public Nullable<decimal> DONoOfPrints { get; set; }
        public string DOvPrintUser { get; set; }
        public Nullable<int> Audited { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditUser { get; set; }
        public Nullable<int> Dispatched { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public string DispatchedUser { get; set; }
        public Nullable<int> Handedover { get; set; }
        public string HandedoverUser { get; set; }
        public Nullable<System.DateTime> HandedoverDate { get; set; }
        public Nullable<int> Completed { get; set; }
        public string CompletedUser { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> PackingListCreated { get; set; }
        public string PackingListNo { get; set; }
        public Nullable<System.DateTime> PackingListDate { get; set; }
        public string PackingListUser { get; set; }
        public string Remarks { get; set; }
        public string HandOverLorry { get; set; }
        public string CompleteRemark { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> Dodate { get; set; }
    }
}
