//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_packingdet
    {
        public string PackingNo { get; set; }
        public string Dono { get; set; }
        public string Customer { get; set; }
        public string Agent { get; set; }
        public Nullable<System.DateTime> datex { get; set; }
        public Nullable<decimal> TTLCartons { get; set; }
    }
}
