//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_packinghead
    {
        public string PackingNo { get; set; }
        public string RefNumber { get; set; }
        public string CompCode { get; set; }
        public string LocaCode { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
        public Nullable<decimal> NoOfCartons { get; set; }
        public string Vehicle { get; set; }
        public string Driver { get; set; }
        public string CreatedUser { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> Processed { get; set; }
        public Nullable<System.DateTime> ProcessedDate { get; set; }
        public string ProcessedUser { get; set; }
        public Nullable<bool> Glupdated { get; set; }
    }
}
