//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smartOffice_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SalesCustomerAlloc
    {
        public string SalesMan { get; set; }
        public string Customer { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> AllocQTY { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> Dateto { get; set; }
        public string Userx { get; set; }
        public Nullable<System.DateTime> Datex { get; set; }
    }
}
